grails-app/domain/evoting/model/QuestionAnswer.groovy
package evoting.model

import java.util.List

class QuestionAnswer implements Serializable {

    static hasMany = [ answerList : Answer ]
    static belongsTo = [ votingAnswer : VotingAnswer ]

    Question question
    List<Answer> answerList = new ArrayList<Answer>()

    static constraints = { answerList(minSize : 1) }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder()
        builder.append(getClass().getName())
        builder.append("[")
        builder.append(System.identityHashCode(this))
        builder.append("] {\n\tquestion: ")
        builder.append(question)
        builder.append("\n\tanswerList: ")
        builder.append(answerList)
        builder.append("\n}")
        return builder.toString()
    }
}

grails-app/controllers/evoting/model/AnswerController.groovy
package evoting.model



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AnswerController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Answer.list(params), model:[answerInstanceCount: Answer.count()]
    }

    def show(Answer answerInstance) {
        respond answerInstance
    }

    def create() {
        respond new Answer(params)
    }

    @Transactional
    def save(Answer answerInstance) {
        if (answerInstance == null) {
            notFound()
            return
        }

        if (answerInstance.hasErrors()) {
            respond answerInstance.errors, view:'create'
            return
        }

        answerInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'answer.label', default: 'Answer'), answerInstance.id])
                redirect answerInstance
            }
            '*' { respond answerInstance, [status: CREATED] }
        }
    }

    def edit(Answer answerInstance) {
        respond answerInstance
    }

    @Transactional
    def update(Answer answerInstance) {
        if (answerInstance == null) {
            notFound()
            return
        }

        if (answerInstance.hasErrors()) {
            respond answerInstance.errors, view:'edit'
            return
        }

        answerInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Answer.label', default: 'Answer'), answerInstance.id])
                redirect answerInstance
            }
            '*'{ respond answerInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Answer answerInstance) {

        if (answerInstance == null) {
            notFound()
            return
        }

        answerInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Answer.label', default: 'Answer'), answerInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'answer.label', default: 'Answer'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/evoting/model/QuestionAnswerController.groovy
package evoting.model



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class QuestionAnswerController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond QuestionAnswer.list(params), model:[questionAnswerInstanceCount: QuestionAnswer.count()]
    }

    def show(QuestionAnswer questionAnswerInstance) {
        respond questionAnswerInstance
    }

    def create() {
        respond new QuestionAnswer(params)
    }

    @Transactional
    def save(QuestionAnswer questionAnswerInstance) {
        if (questionAnswerInstance == null) {
            notFound()
            return
        }

        if (questionAnswerInstance.hasErrors()) {
            respond questionAnswerInstance.errors, view:'create'
            return
        }

        questionAnswerInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'questionAnswer.label', default: 'QuestionAnswer'), questionAnswerInstance.id])
                redirect questionAnswerInstance
            }
            '*' { respond questionAnswerInstance, [status: CREATED] }
        }
    }

    def edit(QuestionAnswer questionAnswerInstance) {
        respond questionAnswerInstance
    }

    @Transactional
    def update(QuestionAnswer questionAnswerInstance) {
        if (questionAnswerInstance == null) {
            notFound()
            return
        }

        if (questionAnswerInstance.hasErrors()) {
            respond questionAnswerInstance.errors, view:'edit'
            return
        }

        questionAnswerInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'QuestionAnswer.label', default: 'QuestionAnswer'), questionAnswerInstance.id])
                redirect questionAnswerInstance
            }
            '*'{ respond questionAnswerInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(QuestionAnswer questionAnswerInstance) {

        if (questionAnswerInstance == null) {
            notFound()
            return
        }

        questionAnswerInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'QuestionAnswer.label', default: 'QuestionAnswer'), questionAnswerInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'questionAnswer.label', default: 'QuestionAnswer'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/questionAnswer/_form.gsp
<%@ page import="evoting.model.QuestionAnswer" %>



<div class="fieldcontain ${hasErrors(bean: questionAnswerInstance, field: 'answerList', 'error')} ">
	<label for="answerList">
		<g:message code="questionAnswer.answerList.label" default="Answer List" />
		
	</label>
	<g:select name="answerList" from="${evoting.model.Answer.list()}" multiple="multiple" optionKey="id" size="5" value="${questionAnswerInstance?.answerList*.id}" class="many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: questionAnswerInstance, field: 'question', 'error')} required">
	<label for="question">
		<g:message code="questionAnswer.question.label" default="Question" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="question" name="question.id" from="${evoting.model.Question.list()}" optionKey="id" required="" value="${questionAnswerInstance?.question?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: questionAnswerInstance, field: 'votingAnswer', 'error')} required">
	<label for="votingAnswer">
		<g:message code="questionAnswer.votingAnswer.label" default="Voting Answer" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="votingAnswer" name="votingAnswer.id" from="${evoting.model.VotingAnswer.list()}" optionKey="id" required="" value="${questionAnswerInstance?.votingAnswer?.id}" class="many-to-one"/>

</div>

grails-app/views/questionAnswer/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'questionAnswer.label', default: 'QuestionAnswer')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-questionAnswer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-questionAnswer" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${questionAnswerInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${questionAnswerInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:questionAnswerInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/questionAnswer/edit.gsp
<%@ page import="evoting.model.QuestionAnswer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'questionAnswer.label', default: 'QuestionAnswer')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-questionAnswer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-questionAnswer" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${questionAnswerInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${questionAnswerInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:questionAnswerInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${questionAnswerInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/questionAnswer/index.gsp
<%@ page import="evoting.model.QuestionAnswer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'questionAnswer.label', default: 'QuestionAnswer')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-questionAnswer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-questionAnswer" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="questionAnswer.question.label" default="Question" /></th>
					
						<th><g:message code="questionAnswer.votingAnswer.label" default="Voting Answer" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${questionAnswerInstanceList}" status="i" var="questionAnswerInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${questionAnswerInstance.id}">${fieldValue(bean: questionAnswerInstance, field: "question")}</g:link></td>
					
						<td>${fieldValue(bean: questionAnswerInstance, field: "votingAnswer")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${questionAnswerInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/questionAnswer/show.gsp
<%@ page import="evoting.model.QuestionAnswer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'questionAnswer.label', default: 'QuestionAnswer')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-questionAnswer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-questionAnswer" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list questionAnswer">
			
				<g:if test="${questionAnswerInstance?.answerList}">
				<li class="fieldcontain">
					<span id="answerList-label" class="property-label"><g:message code="questionAnswer.answerList.label" default="Answer List" /></span>
					
						<g:each in="${questionAnswerInstance.answerList}" var="a">
						<span class="property-value" aria-labelledby="answerList-label"><g:link controller="answer" action="show" id="${a.id}">${a?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${questionAnswerInstance?.question}">
				<li class="fieldcontain">
					<span id="question-label" class="property-label"><g:message code="questionAnswer.question.label" default="Question" /></span>
					
						<span class="property-value" aria-labelledby="question-label"><g:link controller="question" action="show" id="${questionAnswerInstance?.question?.id}">${questionAnswerInstance?.question?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${questionAnswerInstance?.votingAnswer}">
				<li class="fieldcontain">
					<span id="votingAnswer-label" class="property-label"><g:message code="questionAnswer.votingAnswer.label" default="Voting Answer" /></span>
					
						<span class="property-value" aria-labelledby="votingAnswer-label"><g:link controller="votingAnswer" action="show" id="${questionAnswerInstance?.votingAnswer?.id}">${questionAnswerInstance?.votingAnswer?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:questionAnswerInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${questionAnswerInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>