grails-app/controllers/evoting/view/AboutController.groovy
package evoting.view

class AboutController {

    def index() { }
}

grails-app/controllers/evoting/view/CreateController.groovy
package evoting.view

import evoting.model.Answer
import evoting.model.Creator
import evoting.model.Question
import evoting.model.Voter
import evoting.model.Voting
import evoting.parser.AnswerParser
import evoting.token.TokenGenerator

class CreateController {

    static scope = "session"

    def index() {
        redirect(action: "createVoting")
    }

    def createVotingFlow = {

        init {
            action {
                Voting voting = new Voting()
                voting.creator = new Creator()
                log.info("\n\n init voting:\n" + voting)
                flow.voting = voting
                [voting : flow.voting]
            }
            on('success').to("createBasics")
            // on(Exception).to("error")
        }

        createBasics {
            on("createBasics") {
                log.info("params:\n" + params)
                Voting voting = new Voting(params)
                int numberOfVoters = params.int("numberOfVoters")
                int numberOfQuestions = params.int("numberOfQuestions")
                log.info("\n\n createQuestions voting:\n" + voting)
                flow.voting = voting
                flow.numberOfVoters = numberOfVoters
                flow.numberOfQuestions = numberOfQuestions
                [
                    voting : flow.voting,
                    numberOfVoters : flow.numberOfVoters,
                    numberOfQuestions : flow.numberOfQuestions
                ]
            }.to "createQuestions"
        }

        createQuestions {
            on("createSummary") {
                log.info("params:\n" + params)
                flow.voting.properties = params
                log.info("\n\n createSummary flow.voting:\n" + flow.voting)

                for(voter in flow.voting.voterList) {
                    // generujemy tokeny
                    voter.token = TokenGenerator.generateToken()
                }


                for(question in flow.voting.questionList) {
                    // parsujemy pytania
                    List<Answer> answerList = AnswerParser.parse(question.answerString)
                    log.info("\n\n createSummary answerList:\n" + answerList)
                    for(answer in answerList) {
                        question.addToAnswerList(answer)
                    }
                }

                log.info("\n\n createSummary flow.voting:\n" + flow.voting)
                [voting : flow.voting]
            }.to "createSummary"

            on("backToBasics").to "createBasics"
        }

        createSummary {
            action {
                Voting voting = flow.voting
                log.info("\n\n createSummary voting:\n" + voting)
            }
        }
    }
}

grails-app/controllers/evoting/view/EditController.groovy
package evoting.view

class EditController {

    def index() { }
}

grails-app/controllers/evoting/view/SearchController.groovy
package evoting.view

class SearchController {

    def index() { }
}

grails-app/views/layouts/clean-blog.gsp
<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<title>Clean Blog</title>

<!-- Bootstrap Core CSS -->
<link href="${request.contextPath}/clean-blog/css/bootstrap.min.css"
	rel="stylesheet">

<!-- Custom CSS -->
<link href="${request.contextPath}/clean-blog/css/clean-blog.min.css"
	rel="stylesheet">

<!-- Custom Fonts -->
<link
	href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/${request.contextPath}/clean-blog/css/font-awesome.min.css"
	rel="stylesheet" type="text/css">
<link
	href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic'
	rel='stylesheet' type='text/css'>
<link
	href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
	rel='stylesheet' type='text/css'>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

	<!-- Navigation -->
	<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header page-scroll">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<g:link controller="about" class="navbar-brand">About</g:link>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse"
				id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
				    <li><g:link controller="create">Create</g:link></li>
					<li><g:link controller="search">Search</g:link></li>
					<li><g:link controller="participate">Participate</g:link></li>
					<li><g:link controller="edit">Edit</g:link></li>
					<li><g:link controller="view">View</g:link></li>
				</ul>
			</div>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container -->
	</nav>

	<!-- Page Header -->
	<!-- Set your background image for this header on the line below. -->
	<header class="intro-header"
		style="background-image: url('${request.contextPath}/clean-blog/img/home-bg.jpg')">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
					<div class="site-heading">
						<h1>EVoting</h1>
						<hr class="small">
						<span class="subheading">Easy Platform for Voting</span>
					</div>
				</div>
			</div>
		</div>
	</header>

	<div class="container">
		<div class="row">
			<g:layoutBody />
		</div>
	</div>

	<!-- Main Content -->
	<%--
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Man must explore, and this is exploration at its greatest
                        </h2>
                        <h3 class="post-subtitle">
                            Problems look mighty small from 150 miles up
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 24, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
                        </h2>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 18, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Science has not yet mastered prophecy
                        </h2>
                        <h3 class="post-subtitle">
                            We predict too much for the next year and yet far too little for the next ten.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on August 24, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Failure is not an option
                        </h2>
                        <h3 class="post-subtitle">
                            Many say exploration is part of our destiny, but it’s actually our duty to future generations.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on July 8, 2014</p>
                </div>
                <hr>
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    --%>
	<hr>

	<!-- Footer -->
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
					<ul class="list-inline text-center">
						<li><a href="#"> <span class="fa-stack fa-lg"> <i
									class="fa fa-circle fa-stack-2x"></i> <i
									class="fa fa-twitter fa-stack-1x fa-inverse"></i>
							</span>
						</a></li>
						<li><a href="#"> <span class="fa-stack fa-lg"> <i
									class="fa fa-circle fa-stack-2x"></i> <i
									class="fa fa-facebook fa-stack-1x fa-inverse"></i>
							</span>
						</a></li>
						<li><a href="#"> <span class="fa-stack fa-lg"> <i
									class="fa fa-circle fa-stack-2x"></i> <i
									class="fa fa-github fa-stack-1x fa-inverse"></i>
							</span>
						</a></li>
					</ul>
					<p class="copyright text-muted">Copyright &copy; SilverStar 2014</p>
				</div>
			</div>
		</div>
	</footer>

	<!-- jQuery -->
	<script src="${request.contextPath}/clean-blog/js/jquery.js"></script>

	<!-- Bootstrap Core JavaScript -->
	<script src="${request.contextPath}/clean-blog/js/bootstrap.min.js"></script>

	<!-- Custom Theme JavaScript -->
	<script src="${request.contextPath}/clean-blog/js/clean-blog.min.js"></script>

</body>

</html>

grails-app/views/layouts/journal.gsp
<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<title>Easy Voting</title>
<meta content="width=device-width, initial-scale=1" name="viewport">
<meta content="IE=edge" http-equiv="X-UA-Compatible">

<!-- Bootstrap Core CSS -->
<link href="${request.contextPath}/journal/css/bootstrap.min.css"
	rel="stylesheet">

<!-- Custom CSS -->

<g:layoutHead />

</head>
<body>
	<div class="container">

		<div id="banner" class="page-header">
			<div class="row">
				<g:render template="/templates/journal/navbar" />
			</div>
		</div>

		<g:render template="/templates/journal/jumbotron" />

		<g:layoutBody />

	</div>
</body>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
		<g:layoutHead/>
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><asset:image src="grails_logo.png" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
	</body>
</html>