grails-app/controllers/evoting/view/AboutController.groovy
package evoting.view

class AboutController {

    def index() { }
}

grails-app/controllers/evoting/view/CreateController.groovy
package evoting.view

import evoting.model.Answer
import evoting.model.Creator
import evoting.model.Question
import evoting.model.Voter
import evoting.model.Voting
import evoting.parser.AnswerParser
import evoting.token.TokenGenerator

class CreateController {

    static scope = "session"

    def index() {
        redirect(action: "createVoting")
    }

    def createVotingFlow = {

        init {
            action {
                Voting voting = new Voting()
                voting.creator = new Creator()
                log.info("\n\n init voting:\n" + voting)
                flow.voting = voting
                [voting : flow.voting]
            }
            on('success').to("createBasics")
            // on(Exception).to("error")
        }

        createBasics {
            on("createBasics") {
                log.info("params:\n" + params)
                Voting voting = new Voting(params)
                int numberOfVoters = params.int("numberOfVoters")
                int numberOfQuestions = params.int("numberOfQuestions")
                log.info("\n\n createQuestions voting:\n" + voting)
                flow.voting = voting
                flow.numberOfVoters = numberOfVoters
                flow.numberOfQuestions = numberOfQuestions
                [
                    voting : flow.voting,
                    numberOfVoters : flow.numberOfVoters,
                    numberOfQuestions : flow.numberOfQuestions
                ]
            }.to "createQuestions"
        }

        createQuestions {
            on("createSummary") {
                log.info("params:\n" + params)
                flow.voting.properties = params
                log.info("\n\n createSummary flow.voting:\n" + flow.voting)

                for(voter in flow.voting.voterList) {
                    // generujemy tokeny
                    voter.token = TokenGenerator.generateToken()
                }


                for(question in flow.voting.questionList) {
                    // parsujemy pytania
                    List<Answer> answerList = AnswerParser.parse(question.answerString)
                    log.info("\n\n createSummary answerList:\n" + answerList)
                    for(answer in answerList) {
                        question.addToAnswerList(answer)
                    }
                }

                log.info("\n\n createSummary flow.voting:\n" + flow.voting)
                [voting : flow.voting]
            }.to "createSummary"

            on("backToBasics").to "createBasics"
        }

        createSummary {
            action {
                Voting voting = flow.voting
                log.info("\n\n createSummary voting:\n" + voting)
            }
        }
    }
}

grails-app/controllers/evoting/view/EditController.groovy
package evoting.view

class EditController {

    def index() { }
}

grails-app/controllers/evoting/view/HomeController.groovy
package evoting.view

class HomeController {

    def index() { }
}

grails-app/views/templates/journal/_jumbotron.gsp
<div class="jumbotron">
  <h1>EVoting</h1>
  <p></p>
  <p>Easy Platform for Voting</p>
  <g:link controller="about" class="btn btn-primary btn-lg">Learn more</g:link>
</div>

grails-app/views/templates/journal/_navbar.gsp
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"
				data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<g:link controller="about" action="index" class="navbar-brand">About</g:link>
		</div>

		<div class="collapse navbar-collapse"
			id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><g:link controller="home" action="index">Home</g:link></li>
			</ul>
			<form class="navbar-form navbar-left" role="search">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search">
				</div>
				<button type="submit" class="btn btn-default">Submit</button>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<li><g:link controller="create" action="index">Create</g:link></li>
                <li><g:link controller="search" action="index">Search</g:link></li>
                <li><g:link controller="participate" action="index">Participate</g:link></li>
                <li><g:link controller="edit" action="index">Edit</g:link></li>
                <li><g:link controller="view" action="index">View</g:link></li>
			</ul>
		</div>
	</div>
</nav>